Fix error thrown by numpy in py3
Here's the error traceback:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-37-2188dcd1b1a0> in <module>()
     52 x_mesh = np.reshape(np.array(xs),(x_length, y_length))
     53 y_mesh = np.reshape(np.array(ys),(x_length, y_length))
---> 54 z_mesh = np.reshape(np.array(zs),(x_length, y_length))
     55
     56 # Make fancy 3D plot

/home/att/Projects/hypergraph/py3/lib/python3.4/site-packages/numpy/core/fromnumeric.py in reshape(a, newshape, order)
    216     except AttributeError:
    217         return _wrapit(a, 'reshape', newshape, order=order)
--> 218     return reshape(newshape, order=order)
    219
    220

ValueError: total size of new array must be unchanged
```

What's the cause? `dictionary.values()` in python3 is a simple MappingView object
so np.array(zs) has dimention `1`. The simplest way of fixing this is
evaluating `values` as list.

I also improved formatting a bit in this file.